### Base Test

GET https://localhost/

### User Id Test

GET https://localhost/users/id/abcd

### User Username Test

GET https://localhost/users/username/andrew1

### User Create Test

POST https://localhost/users
Content-Type: application/json

{
    "username": "andrew1",
    "password": "password-test"
}

### Posts Id Test

GET http://localhost:4000/posts/id/abcde

### Posts UserId Test

GET http://localhost:4000/posts/user/abcd

### Replies PostId Test

GET http://localhost:4000/posts/replies/abcde

### Follows Get Test

GET http://localhost:4000/followers/abcd

### Follows New User Test

POST http://localhost:4000/followers/abcd
Content-Type: application/json

{
    "followingId": "0"
}
